Code review
Ev1ch/Front-end_School_HW_1 pull request #1
Opened 2021-12-21 22:20 UTC by Ev1ch

2021-12-23 08:31 UTC, Nina-Antoniuk commented on src/components/pages/user/information/index.tsx
> +const Information = ({ user, stats, className }: IInformationProps) => {
компонент з такою назвою уже є src/components/common/tiktuk/**information**/index.tsx, можливо варто обрати назву трохи специфічніше, бо складається враження що в икористовується один і той самий компонент

2021-12-23 08:31 UTC, Nina-Antoniuk commented on src/components/common/tiktuk/index.tsx
> +const TikTuk = ({ tiktuk }: IVideoProps) => {
Назва змінної не зовсім відображає що це за компонент. Можливо варто змінити назву на більш описову (наприклад TikTukPost, абощо).

2021-12-23 08:31 UTC, Nina-Antoniuk commented on src/components/pages/trending/index.tsx
> +            {tiktuks.map((tiktuk: ITikTuk) => (
Зважаючи на те, що тут відбувається рендер однотипних елементів колекції було б більш семантично використовувати список `<ul><li><TikTuk /></li></ul>`

2021-12-23 08:31 UTC, Nina-Antoniuk commented on src/components/pages/user/index.tsx
> +            {feed.map((tiktuk) => (
Зважаючи на те, що тут відбувається рендер однотипних елементів колекції було б більш семантично використовувати список `<ul><li><MinifiedTikTuk/></li></ul>`

2021-12-23 08:31 UTC, Nina-Antoniuk commented on src/components/common/tiktuk/information/index.tsx
> +            {description.hashtags.map((hashtag) => (
Зважаючи на те, що тут відбувається рендер однотипних елементів колекції було б більш семантично використовувати список `<ul><li><Hashtag /></li></ul>`

2021-12-27 11:50 UTC, yurich30 commented on .eslintrc
> +    "@typescript-eslint/explicit-module-boundary-types": "off",
Если мешает какое-то правило, и сложно его поправить, то лучше вместо "off" ставить "warn", чтобы по возможности потом можно было исправить.

2021-12-27 13:10 UTC, yurich30 requested changes

2021-12-27 13:10 UTC, yurich30 commented on .eslintrc
> +    "@typescript-eslint/no-unused-vars": "off",
то же самое

2021-12-27 13:10 UTC, yurich30 commented on .eslintrc
> +    "@typescript-eslint/no-explicit-any": "off",
то же самое

2021-12-27 13:10 UTC, yurich30 commented on .eslintrc
> +    "object-curly-newline": "off",
Это правило я бы тоже не выключал, оно очень влияет на читабельность кода

2021-12-27 13:10 UTC, yurich30 commented on package.json
> +    "@testing-library/jest-dom": "^5.14.1",
devDependencies

2021-12-27 13:10 UTC, yurich30 commented on package.json
> +    "@types/jest": "^26.0.24",
devDependencies

2021-12-27 13:10 UTC, yurich30 commented on package.json
> +    "typescript": "^4.4.4",
devDependencies

2021-12-27 13:10 UTC, yurich30 commented on src/common/constants/index.ts
> +export { default as API_ROOT } from './api';
Зачем?)

2021-12-27 13:10 UTC, yurich30 commented on src/services/user.ts
> +    // await callApi({
Нужно?

2021-12-27 13:10 UTC, yurich30 commented on src/helpers/call-api.ts
> +type TBody = any;
Возможно стоит вынести типы и интерфейсы в отдельный файл?

2021-12-27 13:10 UTC, yurich30 commented on src/containers/user/logic/state.ts
> +export interface IUserInformationState {
Возможно стоит вынести?

2021-12-27 13:10 UTC, yurich30 commented on src/components/modals/loader/index.tsx
> +        <Spinner />
Вот тут непонятно с неймингом Loader spinner, если прям очень нужна эта обертка, то лучше назвать LoaderContainer и Loader (вместо Spinner), или же сделать все в одном компоненте

2021-12-27 13:10 UTC, yurich30 commented on .husky/.gitignore
> +_
Нужно?

2021-12-27 13:25 UTC, Ev1ch commented on .husky/.gitignore
> +_
Так. Тула створює папку з такою назвою, яку потрібно ігнорувати

2021-12-27 13:26 UTC, Ev1ch commented on src/services/user.ts
> +    // await callApi({
Так. Тоді перестав працювати API, тому екстрено змінив на константу

2021-12-27 13:27 UTC, Ev1ch commented on src/common/constants/index.ts
> +export { default as API_ROOT } from './api';
Щоб зручно імпортувати константи із загальної директорії, а не прописувати повний шлях

2021-12-28 16:27 UTC, Ev1ch commented on src/components/modals/loader/index.tsx
> +        <Spinner />
`Spinner` - це сам це елемент, який крутиться. `Loader` - саме модалка1

2021-12-28 16:28 UTC, Ev1ch commented on src/components/pages/user/information/index.tsx
> +const Information = ({ user, stats, className }: IInformationProps) => {
В pull-request'i не сильно видно, але він знаходиться в різних зовсім папках, тобто є контекст того, який інформаційний компонент має бути. Якщо якщо переназвати буде щось типу `/user/user-information` - своєрідне дублювання назвали головного об'єкту

2022-01-03 13:27 UTC, Boooober commented on package.json
> +    "typescript": "^4.4.4",
Так а что решили с devDependencies? Комментарий resolved, но изменений нет?

2022-01-03 13:27 UTC, Boooober commented on src/helpers/call-api.ts
> +  method?: string;
А  чего уже тогда методы не из разрешенного списка?

2022-01-03 13:27 UTC, Boooober commented on src/helpers/call-api.ts
> +  body?: TBody;
`body` опционален даже при `GET` запросе?

2022-01-03 13:27 UTC, Boooober commented on src/helpers/call-api.ts
> +    (string, key, index) => `${string}${index === 0 ? '?' : '&'}${key}=${query[key]}`,
А ты учел экранирование спецсимолов?

2022-01-03 13:27 UTC, Boooober commented on src/helpers/call-api.ts
> +  API_ROOT + endpoint + (query ? getQuery(query) : '');
Лучше посмотри на `new URL` апи

2022-01-03 13:27 UTC, Boooober commented on src/common/enums/http-methods.ts
> +export default HttpMethods;
Немного overhead, ты их и сам используешь только один раз для `GET`)

2022-01-03 13:27 UTC, Boooober commented on src/helpers/call-api.ts
> +  headers['X-RapidAPI-Key'] = process.env.REACT_APP_API_KEY as string;
Хелпер выглядит максимально абстрактно и тут мы встречаем завязку на конкретную среду приложения. Тогда зачем все это?)

2022-01-03 13:27 UTC, Boooober commented on src/helpers/call-api.ts
> +const callApi = async (args: IRequestArgs): Promise<Response> => fetch(getUrl(args), getArgs(args));
Тут async не нужен, для этого даже есть правило в eslint.

Но вот где он пригодился бы, так это если бы мы проверяли тут результат fetch, что он `ok` и ждали бы `response.json()`.
В этом случае данный апи клиент приобрел бы на много больше смысла, чем сейчас

2022-01-03 13:27 UTC, Boooober commented on src/helpers/number-to-minified.ts
> +      convertedNumber = `${isInteger(dividedNumber) ? dividedNumber : dividedNumber.toFixed(1)} ${
`Number.isInteger`

2022-01-03 13:27 UTC, Boooober commented on src/helpers/number-to-minified.ts
> +      convertedNumber = `${isInteger(dividedNumber) ? dividedNumber : dividedNumber.toFixed(1)} ${
Возможно, с остачей от деления было бы проще

2022-01-03 13:27 UTC, Boooober commented on src/helpers/response-error.ts
> +    this.message = message;
можно сократить запись до `constructor(private message: string) {}`

Но лучше, конечно, отталкиваться от встроенных ошибок и расширять их

```
class ResponseError extends Error {
  constructor(message: string, public status = 200) {
    super(message);
  }
}
```

Так он хоть смогут пройти проверку instanceof Error, если нужно будет

2022-01-03 13:27 UTC, Boooober commented on src/helpers/response-error.ts
> +    return this.message;
а какой в этом смысл?)
У тебя же есть поля, методы ничего нового не привносят

2022-01-03 13:27 UTC, Boooober commented on src/services/tiktuks.ts
> +    }).then((response) => response.json());
- А делать, если респонс не `ok`?
 - А почему не везде `async/await`?
 - А если организовать сервис в виде экспорта независимых функций, в скомплированном проекте будет больше или меньше кода? В каком случае лучше бы работал tree-shaking?
Если ты переживаешь за импорты, то в случае с функциями есть два варианта:
   - аналогично вернет объект `TikTuksService` со всеми методами, типо статика
```import * as TikTuksService from 'services/TikTuksService'```
   - точечно подключит нужные
```import { getMany } from 'services/TikTuksService'```

2022-01-03 13:27 UTC, Boooober commented on src/services/user.ts
> +    // await callApi({
Было бы здорово тогда уже сделать env флажок, запускаемся на моках или настоящем API.

Но супер здорово, это было бы настроить дев сервер с прокси, чтобы клиентский код знал только про один источник данных. В реалиях этой работы оно того не стоит, просто поделился мыслями)

2022-01-03 13:27 UTC, Boooober commented on src/styles/fonts.scss
> +@import url('https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&family=Roboto:ital,wght@0,100;0,300;0,
Ты все эти шрифты используешь? Они же будут грузиться очень долго

2022-01-03 13:27 UTC, Boooober commented on src/styles/variables.scss
> +:root {
из того что я заметил, у тебя css переменные объявились уже как минимум 6 раза:
`src/styles/index.scss`
`src/styles/common.scss`
`src/components/common/tiktuk/information/information.module.scss`
`src/components/common/tiktuk/panel/panel.module.scss`
`src/components/pages/user/information/information.module.scss`
`src/components/pages/user/user.module.scss`

2022-01-03 13:27 UTC, Boooober commented on src/types/feed.ts
> +}
И ты все эти поля используешь в своем приложении?

2022-01-03 13:27 UTC, Boooober commented on tsconfig.json
> +    "baseUrl": "./src"
Много сломается, если включишь `strictNullChecks`?)

2022-01-03 13:27 UTC, Boooober commented on src/services/tiktuks.ts
> +      endpoint: ApiRoutes.FEED,
Не уверен, что оно того стоило, выносить все ендпоинты в `ApiRoutes` ради одного использования.

Однако, возможно, вопрос вкусовщины?

2022-01-03 13:27 UTC, Boooober commented on src/helpers/number-to-minified.ts
> +  [key: string]: IStage;
Лучше `Record<string, IStage>`
И я такое пишу сразу в переменной, отдельный тип не выношу, лаконичнее выглядит, тем более, что не переиспользуется.

2022-01-03 13:27 UTC, Boooober commented on src/helpers/call-api.ts
> +      throw new Error('GET request does not support request body.');
эту ошибку можно было отловить при статических проверках, а не в рантайме

2022-01-03 13:27 UTC, Boooober commented on src/helpers/call-api.ts
> +  [key: string]: string | number;
`Record<string, string | number>`

2022-01-03 13:27 UTC, Boooober commented on src/helpers/call-api.ts
> +type TBody = any;
`any` или, может быть, `unknown`?

2022-01-03 13:27 UTC, Boooober commented on src/containers/user/logic/index.ts
> +      ...feed,
у тебя же `@reduxjs/toolkit`, почему ты не "мутирушь" state?

2022-01-03 13:27 UTC, Boooober commented on src/containers/user/logic/actions.ts
> +export const setLoading = createAction<actionsTypes.ISetLoadingArgs>(actionsTypes.SET_LOADING);
у тебя же `@reduxjs/toolkit`, почему ты не используешь `createSlice`?
Он бы тебе создал сразу `reducer`, `action` и `action creator`

2022-01-03 13:27 UTC, Boooober commented on src/components/common/tiktuk/panel/index.tsx
> +const Panel = function Panel({ likes, comments, shares }: IPanelProps) {
Просто интересно, а почему не `arrow function`?

2022-01-03 13:27 UTC, Boooober commented on src/components/common/tiktuk/information/index.tsx
> +            {description.hashtags.map((hashtag) => (
соглы

2022-01-04 11:06 UTC, Ev1ch commented on src/components/common/tiktuk/panel/index.tsx
> +const Panel = function Panel({ likes, comments, shares }: IPanelProps) {
Поставив плагіни для Eslint'a з лекції, вони вимагали саме такий запис компонентів. Так і зробив

2022-01-04 11:22 UTC, Ev1ch commented on src/styles/variables.scss
> +:root {
> из того что я заметил, у тебя css переменные объявились уже как минимум 6 раза: `src/styles/index.scss` `src/styles/common.scss` `src/components/common/tiktuk/information/information.module.scss` `src/components/common/tiktuk/panel/panel.module.scss` `src/components/pages/user/information/information.module.scss` `src/components/pages/user/user.module.scss`

Ні, встановлюю я змінні тут та під'єдную цей файл у корінь додатку. А у інших компонентах я використовую ці змінні, не встановлюю

2022-01-15 16:43 UTC, Ev1ch commented on src/helpers/number-to-minified.ts
> +      convertedNumber = `${isInteger(dividedNumber) ? dividedNumber : dividedNumber.toFixed(1)} ${
В мене якось простіше не вийшло

2022-01-20 17:05 UTC, merged